//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_MyAssets/4.Input/AttackInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AttackInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AttackInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AttackInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerAttacks"",
            ""id"": ""f270fb62-8fee-4db1-a46f-2932c0edc919"",
            ""actions"": [
                {
                    ""name"": ""Slash"",
                    ""type"": ""Button"",
                    ""id"": ""82c626ac-5736-46ae-88d0-a6c8e23baa32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""45ba6843-99d5-4ddf-981b-0859d6721f97"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerAttacks
        m_PlayerAttacks = asset.FindActionMap("PlayerAttacks", throwIfNotFound: true);
        m_PlayerAttacks_Slash = m_PlayerAttacks.FindAction("Slash", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerAttacks
    private readonly InputActionMap m_PlayerAttacks;
    private List<IPlayerAttacksActions> m_PlayerAttacksActionsCallbackInterfaces = new List<IPlayerAttacksActions>();
    private readonly InputAction m_PlayerAttacks_Slash;
    public struct PlayerAttacksActions
    {
        private @AttackInputs m_Wrapper;
        public PlayerAttacksActions(@AttackInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Slash => m_Wrapper.m_PlayerAttacks_Slash;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAttacks; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerAttacksActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerAttacksActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerAttacksActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerAttacksActionsCallbackInterfaces.Add(instance);
            @Slash.started += instance.OnSlash;
            @Slash.performed += instance.OnSlash;
            @Slash.canceled += instance.OnSlash;
        }

        private void UnregisterCallbacks(IPlayerAttacksActions instance)
        {
            @Slash.started -= instance.OnSlash;
            @Slash.performed -= instance.OnSlash;
            @Slash.canceled -= instance.OnSlash;
        }

        public void RemoveCallbacks(IPlayerAttacksActions instance)
        {
            if (m_Wrapper.m_PlayerAttacksActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerAttacksActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerAttacksActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerAttacksActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerAttacksActions @PlayerAttacks => new PlayerAttacksActions(this);
    public interface IPlayerAttacksActions
    {
        void OnSlash(InputAction.CallbackContext context);
    }
}
